const Costas = [
    { id: 1, name: 'Puxada Aberta na Polia Alta' },
    { id: 2, name: 'Puxada Fechada na Polia Alta' },
    { id: 3, name: 'Puxada com Pegada Supinada' },
    { id: 4, name: 'Remada Curvada com Barra' },
    { id: 5, name: 'Remada Unilateral com Haltere' },
    { id: 6, name: 'Remada na Máquina' },
    { id: 7, name: 'Remada na Polia Baixa' },
    { id: 8, name: 'Remada Serrilhada' },
    { id: 9, name: 'Remada em T' },
    { id: 10, name: 'Remada na Máquina Smith' },
    { id: 11, name: 'Pull Over com Haltere' },
    { id: 12, name: 'Pull Over na Polia Alta' },
    { id: 13, name: 'Barra Fixa com Pegada Aberta' },
    { id: 14, name: 'Barra Fixa com Pegada Fechada' },
    { id: 15, name: 'Barra Fixa com Pegada Supinada' },
    { id: 16, name: 'Face Pull na Polia Alta' },
    { id: 17, name: 'Shrug (Encolhimento) com Halteres' },
    { id: 18, name: 'Shrug (Encolhimento) com Barra' },
    { id: 19, name: 'Shrug na Máquina Smith' },
    { id: 20, name: 'Hiperextensão Lombar' },
    { id: 21, name: 'Good Morning' },
    { id: 22, name: 'Levantamento Terra' },
    { id: 23, name: 'Levantamento Terra Sumô' },
    { id: 24, name: 'Levantamento Terra com Halteres' },
    { id: 25, name: 'Deadlift no Cabo' },
    { id: 26, name: 'Puxada na Máquina Hammer' },
    { id: 27, name: 'Pulldown com Corda' },
    { id: 28, name: 'Remada Invertida no TRX' },
    { id: 29, name: 'Remada Invertida na Barra Fixa' },
    { id: 30, name: 'Scapular Pull-up' }
];

export default Costas;
