const Peito = [
    { id: 1, name: 'Crucifixo com Cabos' },
    { id: 2, name: 'Crucifixo Invertido' },
    { id: 3, name: 'Crucifixo no Banco Declinado' },
    { id: 4, name: 'Crucifixo no Banco Inclinado' },
    { id: 5, name: 'Crucifixo no Banco Plano' },
    { id: 6, name: 'Flexão de Braço' },
    { id: 7, name: 'Flexão de Braço com Bola de Estabilidade' },
    { id: 8, name: 'Flexão de Braço com Clap' },
    { id: 9, name: 'Flexão de Braço com Mão Fechada' },
    { id: 10, name: 'Flexão de Braço com Pés Elevados' },
    { id: 11, name: 'Flexão de Braço em Declínio' },
    { id: 12, name: 'Fly' },
    { id: 13, name: 'Mergulho em Barras Paralelas' },
    { id: 14, name: 'Mergulho na Máquina' },
    { id: 15, name: 'Pec Deck (Borboleta)' },
    { id: 16, name: 'Press de Peito no Cabo em Pé' },
    { id: 17, name: 'Pull Over com Barra' },
    { id: 18, name: 'Pull Over com Haltere' },
    { id: 19, name: 'Pull Over no Cabo' },
    { id: 20, name: 'Supino Articulado' },
    { id: 21, name: 'Supino com Pegada Fechada' },
    { id: 22, name: 'Supino com Pegada Inversa' },
    { id: 23, name: 'Supino Declinado com Barra' },
    { id: 24, name: 'Supino Declinado com Halteres' },
    { id: 25, name: 'Supino Inclinado com Barra' },
    { id: 26, name: 'Supino Inclinado com Halteres' },
    { id: 27, name: 'Supino Inclinado Guidado' },
    { id: 28, name: 'Supino na Máquina de Musculação' },
    { id: 29, name: 'Supino na Máquina Hammer' },
    { id: 30, name: 'Supino na Máquina Smith' },
    { id: 31, name: 'Supino Reto com Barra' },
    { id: 32, name: 'Supino Reto com Halteres' },
    { id: 33, name: 'Supino Reto Guidado' },
    { id: 34, name: 'Svend Press' },
];

export default Peito;